name: Build
on:
  push:
    branches:
      - 'default'
      - 'v[0-9]+'

jobs:
  build:
    runs-on: blacksmith-16vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - uses: EndBug/add-and-commit@v9
        with:
          add: dist
          message: Rebuild (automated)
