name: Bump Tags on Default

on:
  push:
    branches:
      - default

jobs:
  bump-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update v3 and v3.0.1 tags
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git tag -fa v3 -m "Update v3 tag to latest commit on default"
          git tag -fa v3.0.1 -m "Update v3.0.1 tag to latest commit on default"
          git push origin v3 v3.0.1 --force

      - name: Send Slack notification on success
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "text": "Updated setup-ruby v3 and v3.0.1 tags to the latest commit on default"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.CACHE_SLACK_WEBHOOK_URL }}
