name: CI
on: push
jobs:
  test:
    name: Unit tests
    runs-on: blacksmith-8vcpu-ubuntu-2204
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test

  smoke-test:
    name: Build test
    strategy:
      fail-fast: false
      matrix:
        os: [blacksmith-4vcpu-ubuntu-2204, macos-latest, windows-latest]
        zig-version: [0.7.0, 0.8.0, 0.9.0, 0.10.0, 0.11.0]
        include:
          - os: blacksmith-4vcpu-ubuntu-2204
            zig-version: 0.5.0
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Zig
        uses: useblacksmith/setup-zig@v3
        with:
          version: ${{matrix.zig-version}}
      - name: Run tests (zig up to v0.10.x)
        if: ${{ !startsWith(matrix.zig-version, '0.11.') }}
        run: zig build test
        working-directory: test/v0.10
      - name: Run tests (zig v0.11.x)
        if: ${{ startsWith(matrix.zig-version, '0.11.') }}
        run: zig build test
        working-directory: test/v0.11
